[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { path = "/home/fabian/git/_ext/gdextension/godot", features = ["formatted", "trace"] }
